<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UniversalProduct;
use App\Models\MedicineCategory;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UniversalProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Truncate universal_products to refresh catalog
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        UniversalProduct::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Get category lookup map by name
        $categoryMap = MedicineCategory::pluck('id', 'name')->toArray();

        $products = [
            // -------------------------------------------------------------
            // TABLETS (1-25)
            // -------------------------------------------------------------
            [
                'name' => 'Paracetamol 500mg Tablet',
                'description' => 'Effective pain reliever and fever reducer.',
                'salt_composition' => 'Paracetamol IP 500mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Dolo 650mg Tablet',
                'description' => 'Analgesic and antipyretic medication used for fever and moderate pain relief.',
                'salt_composition' => 'Paracetamol 650mg',
                'manufacturer' => 'Micro Labs Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Calpol 500mg Tablet',
                'description' => 'Fever and mild to moderate pain relief tablet.',
                'salt_composition' => 'Paracetamol 500mg',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Azithromycin 500mg Tablet (Azee 500)',
                'description' => 'Macrolide antibiotic used for respiratory and soft tissue bacterial infections.',
                'salt_composition' => 'Azithromycin Dihydrate 500mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Pantoprazole 40mg Tablet (Pan 40)',
                'description' => 'Proton pump inhibitor for acid reflux, acidity, and stomach ulcers.',
                'salt_composition' => 'Pantoprazole Sodium 40mg',
                'manufacturer' => 'Alkem Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Cetirizine 10mg Tablet (Cetzine)',
                'description' => 'Antihistamine for allergic rhinitis, sneezing, and skin allergies.',
                'salt_composition' => 'Cetirizine Dihydrochloride 10mg',
                'manufacturer' => 'Dr. Reddys Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Combiflam Tablet',
                'description' => 'Dual action analgesic for head, muscle, and body aches.',
                'salt_composition' => 'Ibuprofen 400mg + Paracetamol 325mg',
                'manufacturer' => 'Sanofi India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Telmisartan 40mg Tablet (Telma 40)',
                'description' => 'Angiotensin II receptor blocker used in hypertension management.',
                'salt_composition' => 'Telmisartan 40mg',
                'manufacturer' => 'Glenmark Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Metformin 500mg SR Tablet (Glycomet 500)',
                'description' => 'Sustained-release oral anti-diabetic medication for type 2 diabetes.',
                'salt_composition' => 'Metformin Hydrochloride 500mg SR',
                'manufacturer' => 'USV Private Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Montelukast & Levocetirizine Tablet (Monticope)',
                'description' => 'Combination therapy for allergic rhinitis and asthma symptom relief.',
                'salt_composition' => 'Montelukast 10mg + Levocetirizine 5mg',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Atorvastatin 10mg Tablet (Atorva 10)',
                'description' => 'Statin medication to lower blood cholesterol and triglyceride levels.',
                'salt_composition' => 'Atorvastatin Calcium 10mg',
                'manufacturer' => 'Zydus Cadila',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Amoxicillin & Clavulanate 625mg Tablet (Moxikind-CV 625)',
                'description' => 'Penicillin-type antibiotic boosted with beta-lactamase inhibitor.',
                'salt_composition' => 'Amoxicillin 500mg + Clavulanic Acid 125mg',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30041010',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Ciprofloxacin 500mg Tablet (Ciplox 500)',
                'description' => 'Fluoroquinolone antibiotic for UTI, typhoid, and GI tract infections.',
                'salt_composition' => 'Ciprofloxacin Hydrochloride 500mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Ofloxacin 200mg Tablet (Oflox 200)',
                'description' => 'Broad-spectrum synthetic antibacterial medication.',
                'salt_composition' => 'Ofloxacin 200mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Ranitidine 150mg Tablet (Rantac 150)',
                'description' => 'H2 blocker antacid for reducing gastric acid secretion.',
                'salt_composition' => 'Ranitidine Hydrochloride 150mg',
                'manufacturer' => 'J.B. Chemicals & Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Aceclofenac & Paracetamol Tablet (Zerodol-P)',
                'description' => 'Analgesic and anti-inflammatory combination for dental and joint pain.',
                'salt_composition' => 'Aceclofenac 100mg + Paracetamol 325mg',
                'manufacturer' => 'Ipca Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Aceclofenac, Paracetamol & Serratiopeptidase Tablet (Zerodol-SP)',
                'description' => 'Triple action anti-inflammatory, pain reliever, and anti-edema enzyme tablet.',
                'salt_composition' => 'Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg',
                'manufacturer' => 'Ipca Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Diclofenac & Paracetamol Tablet (Voveran Plus)',
                'description' => 'Potent non-steroidal anti-inflammatory pain reliever.',
                'salt_composition' => 'Diclofenac Sodium 50mg + Paracetamol 325mg',
                'manufacturer' => 'Novartis India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Amlodipine 5mg Tablet (Stamlo 5)',
                'description' => 'Calcium channel blocker antihypertensive for blood pressure management.',
                'salt_composition' => 'Amlodipine Besylate 5mg',
                'manufacturer' => 'Dr. Reddys Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Glimepiride 1mg Tablet (Amaryl 1mg)',
                'description' => 'Sulfonylurea oral hypoglycemic medication for type 2 diabetes.',
                'salt_composition' => 'Glimepiride 1mg',
                'manufacturer' => 'Sanofi India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Ondansetron 4mg MD Tablet (Emeset 4 MD)',
                'description' => 'Fast-dissolving antiemetic for nausea and vomiting control.',
                'salt_composition' => 'Ondansetron Hydrochloride 4mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Drotaverine & Mefenamic Acid Tablet (Drotin-M)',
                'description' => 'Antispasmodic and analgesic for abdominal cramps and menstrual period pain.',
                'salt_composition' => 'Drotaverine HCl 80mg + Mefenamic Acid 250mg',
                'manufacturer' => 'Walter Bushnell',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Albendazole 400mg Tablet (Zentel)',
                'description' => 'Broad-spectrum anthelmintic for intestinal worm infestation treatment.',
                'salt_composition' => 'Albendazole 400mg',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Ivermectin 12mg Tablet (Iverchem 12)',
                'description' => 'Antiparasitic tablet for scabies and filariasis management.',
                'salt_composition' => 'Ivermectin 12mg',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],
            [
                'name' => 'Chlorthalidone 12.5mg Tablet (Chlorthal 12.5)',
                'description' => 'Thiazide-like diuretic antihypertensive medication.',
                'salt_composition' => 'Chlorthalidone 12.5mg',
                'manufacturer' => 'Torrent Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Tablet',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // CAPSULES (26-45)
            // -------------------------------------------------------------
            [
                'name' => 'Amoxicillin 500mg Capsule (Mox 500)',
                'description' => 'Broad-spectrum penicillin antibiotic for bacterial infections.',
                'salt_composition' => 'Amoxicillin Trihydrate 500mg',
                'manufacturer' => 'Sun Pharma',
                'hsn_code' => '30041010',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Omeprazole 20mg Capsule (Omez 20)',
                'description' => 'Proton pump inhibitor used to treat GERD, heartburn, and ulcers.',
                'salt_composition' => 'Omeprazole 20mg',
                'manufacturer' => 'Dr. Reddys Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Rabeprazole & Domperidone SR Capsule (Rabeloc-DSR)',
                'description' => 'Combination PPI and prokinetic for hyperacidity with nausea.',
                'salt_composition' => 'Rabeprazole 20mg + Domperidone 30mg SR',
                'manufacturer' => 'Torrent Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Multivitamin & Mineral Capsules (Becadexamin)',
                'description' => 'Daily nutritional dietary supplement supporting stamina and immunity.',
                'salt_composition' => 'Essential Vitamins + Minerals + Zinc',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '21069099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Becosules Performance Capsule',
                'description' => 'Vitamin B-Complex with Vitamin C and L-Glutamic acid supplement.',
                'salt_composition' => 'B-Complex + Vitamin C + Minerals',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Doxycycline 100mg Capsule (Doxicip 100)',
                'description' => 'Tetracycline antibiotic for acne, cholera, and respiratory infections.',
                'salt_composition' => 'Doxycycline Hyclate 100mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Itraconazole 100mg Capsule (Candiforce 100)',
                'description' => 'Broad-spectrum triazole antifungal medication for skin and nail infections.',
                'salt_composition' => 'Itraconazole 100mg',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Itraconazole 200mg Capsule (Candiforce 200)',
                'description' => 'High potency systemic antifungal capsule for persistent fungal dermatoses.',
                'salt_composition' => 'Itraconazole 200mg',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Carbonyl Iron, Folic Acid & Zinc Capsule (Autrin)',
                'description' => 'Hematinic capsule for treating iron deficiency anemia during pregnancy.',
                'salt_composition' => 'Carbonyl Iron 100mg + Folic Acid 1.5mg + Zinc Sulfate 61.8mg',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Pre-probiotic Capsules (Darolac)',
                'description' => 'Probiotic supplement to restore gut microflora balance after antibiotic therapy.',
                'salt_composition' => 'Lactobacillus Rhamnosus + Bifidobacterium Longum',
                'manufacturer' => 'Aristo Pharmaceuticals',
                'hsn_code' => '21069099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Tramadol & Paracetamol Capsule (Ultracet)',
                'description' => 'Opioid and non-opioid combination analgesic for moderate to severe pain.',
                'salt_composition' => 'Tramadol HCl 37.5mg + Paracetamol 325mg',
                'manufacturer' => 'Janssen / Johnson & Johnson',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H1',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Pregabalin 75mg & Methylcobalamin Capsule (Pregeb-M 75)',
                'description' => 'Neuropathic pain reliever for diabetic neuropathy and nerve damage.',
                'salt_composition' => 'Pregabalin 75mg + Methylcobalamin 750mcg',
                'manufacturer' => 'Torrent Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Silodosin 8mg Capsule (Silofast 8)',
                'description' => 'Alpha-1 blocker for benign prostatic hyperplasia (BPH) symptom treatment.',
                'salt_composition' => 'Silodosin 8mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Tacrolimus 1mg Capsule (Tacrograf 1)',
                'description' => 'Immunosuppressant medication used in organ transplant recipients.',
                'salt_composition' => 'Tacrolimus 1mg',
                'manufacturer' => 'Biocon Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Clindamycin 300mg Capsule (Dalacin C)',
                'description' => 'Lincosamide antibiotic for anaerobic and staphylococcal infections.',
                'salt_composition' => 'Clindamycin Hydrochloride 300mg',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Cephalexin 500mg Capsule (Sporidex 500)',
                'description' => '1st generation cephalosporin antibiotic for respiratory and UTI treatment.',
                'salt_composition' => 'Cephalexin Monohydrate 500mg',
                'manufacturer' => 'Sun Pharma',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Vitamin E 400mg Capsule (Evion 400)',
                'description' => 'Antioxidant Vitamin E dietary supplement for skin and cell health.',
                'salt_composition' => 'Tocopheryl Acetate 400mg',
                'manufacturer' => 'Procter & Gamble (P&G)',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Cod Liver Oil 300mg Softgel Capsule (Seven Seas)',
                'description' => 'Natural source of Omega-3 fatty acids, Vitamin A, and Vitamin D.',
                'salt_composition' => 'Cod Liver Oil 300mg',
                'manufacturer' => 'Merck Ltd',
                'hsn_code' => '21069099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Calcium & Vitamin D3 Softgel Capsule (Shelcal 500)',
                'description' => 'Calcium supplement for bone mineral density and osteoporosis prevention.',
                'salt_composition' => 'Elemental Calcium 500mg + Vitamin D3 250 IU',
                'manufacturer' => 'Torrent Pharmaceuticals',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],
            [
                'name' => 'Grape Seed Extract & Antioxidant Capsule (Oxra-G)',
                'description' => 'Potent herbal antioxidant capsule for cardiovascular and vascular support.',
                'salt_composition' => 'Grape Seed Extract 50mg + Vitamin C + Vitamin E',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '21069099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Capsule',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // SYRUPS (46-60)
            // -------------------------------------------------------------
            [
                'name' => 'Benadryl Cough Syrup 100ml',
                'description' => 'Relieves cough, throat irritation, and nasal congestion symptoms.',
                'salt_composition' => 'Diphenhydramine HCl 14mg + Ammonium Chloride 138mg',
                'manufacturer' => 'Johnson & Johnson',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Ascoril LS Expectorant 100ml',
                'description' => 'Mucolytic and bronchodilator syrup for productive wet chesty cough.',
                'salt_composition' => 'Levosalbutamol 1mg + Ambroxol 30mg + Guaiphenesin 50mg',
                'manufacturer' => 'Glenmark Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Gelusil Antacid Syrup 200ml',
                'description' => 'Quick action antacid and antiflatulent liquid syrup for acid reflux.',
                'salt_composition' => 'Aluminium Hydroxide + Magnesium Hydroxide + Dimethicone',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Corex DX Cough Syrup 100ml',
                'description' => 'Non-drowsy dry cough suppressant syrup.',
                'salt_composition' => 'Dextromethorphan HBr 10mg + Chlorpheniramine Maleate 4mg',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Grilinctus BM Syrup 100ml',
                'description' => 'Bronchodilator and mucolytic syrup for asthma and bronchitis cough.',
                'salt_composition' => 'Terbutaline Sulfate 1.25mg + Bromhexine HCl 4mg',
                'manufacturer' => 'Franco-Indian Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Alex Cough Syrup 100ml',
                'description' => 'Effective cough syrup for dry and irritating throat cough.',
                'salt_composition' => 'Phenylephrine 5mg + Chlorpheniramine 2mg + Dextromethorphan 10mg',
                'manufacturer' => 'Glenmark Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Lactulose Solution Syrup 200ml (Duphalac)',
                'description' => 'Osmotic laxative syrup for acute and chronic constipation relief.',
                'salt_composition' => 'Lactulose 3.33g / 5ml',
                'manufacturer' => 'Abbott Healthcare',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Multivitamin Syrup for Kids 200ml (Zincovit Syrup)',
                'description' => 'Growth and appetite stimulant multivitamin syrup enriched with zinc.',
                'salt_composition' => 'Multivitamins + Multiminerals + Zinc',
                'manufacturer' => 'Apex Laboratories',
                'hsn_code' => '21069099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Cyproheptadine & Tricholine Citrate Syrup (Ciplactin)',
                'description' => 'Appetite enhancer and anti-allergic liquid tonic.',
                'salt_composition' => 'Cyproheptadine HCl 2mg + Tricholine Citrate 275mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Fungal Diastase & Pepsin Digestive Syrup (Aristozyme)',
                'description' => 'Enzyme tonic for indigestion, bloating, and loss of appetite.',
                'salt_composition' => 'Fungal Diastase 50mg + Pepsin 10mg / 5ml',
                'manufacturer' => 'Aristo Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Iron & Folic Acid Tonic Syrup (Dexorange Syrup)',
                'description' => 'Hematinic syrup for anemia, general weakness, and post-illness recovery.',
                'salt_composition' => 'Ferric Ammonium Citrate 160mg + Folic Acid 0.5mg + Vitamin B12 7.5mcg',
                'manufacturer' => 'Franco-Indian Pharmaceuticals',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Sucralfate & Oxetacaine Suspension Syrup (Sucrafil-O)',
                'description' => 'Mucosal protectant and local anesthetic syrup for gastritis and ulcer pain.',
                'salt_composition' => 'Sucralfate 1g + Oxetacaine 20mg / 10ml',
                'manufacturer' => 'Fourrts India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Calcium & Vitamin D3 Syrup for Children 200ml (Ostocalcium)',
                'description' => 'Pediatric bone health and teeth development calcium syrup.',
                'salt_composition' => 'Elemental Calcium 82mg + Vitamin D3 200 IU / 5ml',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Levocetirizine & Ambroxol Syrup (Ambrodil-LX)',
                'description' => 'Expectorant mucolytic and antihistamine syrup for respiratory cough.',
                'salt_composition' => 'Levocetirizine 2.5mg + Ambroxol 30mg / 5ml',
                'manufacturer' => 'Aristo Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Syrup',
                'verified' => true,
            ],
            [
                'name' => 'Ayurvedic Cough Syrup 100ml (Koflet Syrup)',
                'description' => 'Herbal cough syrup enriched with Holy Basil and Honey.',
                'salt_composition' => 'Tulsi (Ocimum Sanctum) + Madhu (Honey) + Vasaka',
                'manufacturer' => 'Himalaya Wellness',
                'hsn_code' => '30049011',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Syrup',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // SUSPENSIONS (61-70)
            // -------------------------------------------------------------
            [
                'name' => 'Augmentin Duo Oral Suspension 30ml',
                'description' => 'Pediatric antibiotic suspension for ear, throat, and chest bacterial infections.',
                'salt_composition' => 'Amoxicillin 200mg + Clavulanic Acid 28.5mg / 5ml',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30041010',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Paracetamol Oral Suspension 60ml (Crocin Paediatric)',
                'description' => 'Pediatric fever reducer and mild pain analgesic drop suspension.',
                'salt_composition' => 'Paracetamol 120mg / 5ml',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Mefenamic Acid & Paracetamol Suspension (Meftal-P)',
                'description' => 'Anti-inflammatory and antipyretic oral suspension for pediatric fever.',
                'salt_composition' => 'Mefenamic Acid 100mg + Paracetamol 250mg / 5ml',
                'manufacturer' => 'Blue Cross Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Ibupal Oral Suspension 100ml (Ibugesic Plus)',
                'description' => 'Pediatric analgesic suspension for juvenile arthritis and high fever.',
                'salt_composition' => 'Ibuprofen 100mg + Paracetamol 162.5mg / 5ml',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Magaldrate & Simethicone Oral Suspension (Digene Syrup)',
                'description' => 'Antacid liquid suspension neutralizing stomach acid and gas.',
                'salt_composition' => 'Magaldrate 480mg + Simethicone 20mg / 5ml',
                'manufacturer' => 'Abbott Healthcare',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Deflazacort Oral Suspension (Defcort 6ml)',
                'description' => 'Glucocorticoid steroid suspension for severe allergic and autoimmune conditions.',
                'salt_composition' => 'Deflazacort 6mg / 5ml',
                'manufacturer' => 'Macleods Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Azithromycin Oral Suspension 15ml (Azee Suspension)',
                'description' => 'Pediatric macrolide antibiotic suspension for respiratory tract infections.',
                'salt_composition' => 'Azithromycin 200mg / 5ml',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Ofloxacin & Metronidazole Suspension (O2 Suspension)',
                'description' => 'Combination antibiotic and antiprotozoal suspension for diarrhea and dysentery.',
                'salt_composition' => 'Ofloxacin 50mg + Metronidazole 100mg / 5ml',
                'manufacturer' => 'Medley Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Zinc Acetate Pediatric Drops/Suspension (Zinconia)',
                'description' => 'Zinc supplement drops for pediatric diarrhea recovery.',
                'salt_composition' => 'Elemental Zinc 20mg / 5ml',
                'manufacturer' => 'FDC Ltd',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Suspension',
                'verified' => true,
            ],
            [
                'name' => 'Ondansetron Oral Suspension 30ml (Emeset Suspension)',
                'description' => 'Pediatric antiemetic suspension preventing nausea and gastroenteritis vomiting.',
                'salt_composition' => 'Ondansetron 2mg / 5ml',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Suspension',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // INJECTIONS (71-80)
            // -------------------------------------------------------------
            [
                'name' => 'Insulin Glargine 100IU/ml Injection (Lantus)',
                'description' => 'Long-acting basal insulin analog for diabetes mellitus control.',
                'salt_composition' => 'Recombinant Human Insulin Glargine 100IU',
                'manufacturer' => 'Sanofi India',
                'hsn_code' => '30043110',
                'gst_rate' => 5.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Ceftriaxone 1g Injection (Monocef 1g)',
                'description' => '3rd generation cephalosporin antibiotic injection for severe systemic infections.',
                'salt_composition' => 'Ceftriaxone Sodium 1g',
                'manufacturer' => 'Aristo Pharmaceuticals',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H1',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Diclofenac Sodium Injection 75mg/1ml (Voveran AQ)',
                'description' => 'Fast-acting NSAID analgesic injection for post-operative and acute colic pain.',
                'salt_composition' => 'Diclofenac Sodium 75mg',
                'manufacturer' => 'Novartis India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Human Actrapid Insulin 100IU/ml Injection',
                'description' => 'Short-acting soluble human insulin injection for blood glucose spikes.',
                'salt_composition' => 'Soluble Human Insulin 100IU/ml',
                'manufacturer' => 'Novo Nordisk',
                'hsn_code' => '30043110',
                'gst_rate' => 5.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Meropenem 1g Injection (Meronem 1g)',
                'description' => 'Carbapenem broad-spectrum IV antibiotic for ICU and multi-resistant bacterial infections.',
                'salt_composition' => 'Meropenem Trihydrate 1g',
                'manufacturer' => 'Pfizer Ltd',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H1',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Piperacillin & Tazobactam 4.5g Injection (Tazact 4.5)',
                'description' => 'Extended spectrum penicillin + beta-lactamase inhibitor IV injection.',
                'salt_composition' => 'Piperacillin 4g + Tazobactam 500mg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30041010',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H1',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Pantoprazole 40mg IV Injection (Pan-IV)',
                'description' => 'Intravenous PPI injection for active gastrointestinal hemorrhage and acute GERD.',
                'salt_composition' => 'Pantoprazole Sodium 40mg',
                'manufacturer' => 'Alkem Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Iron Sucrose 100mg/5ml Injection (Orofer FCM)',
                'description' => 'Intravenous iron complex injection for severe anemia.',
                'salt_composition' => 'Ferric Carboxymaltose / Iron Sucrose 100mg',
                'manufacturer' => 'Emcure Pharmaceuticals',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Tetanus Toxoid Vaccine Injection 0.5ml',
                'description' => 'Active immunization vaccine against tetanus infection caused by contaminated wounds.',
                'salt_composition' => 'Tetanus Toxoid Absorbed 5 LF',
                'manufacturer' => 'Serum Institute of India',
                'hsn_code' => '30022010',
                'gst_rate' => 5.00,
                'drug_schedule' => 'OTC',
                'category' => 'Injection',
                'verified' => true,
            ],
            [
                'name' => 'Methylcobalamin 1500mcg Injection (Nurokind-OD)',
                'description' => 'Vitamin B12 parenterally administered injection for severe neuropathy.',
                'salt_composition' => 'Methylcobalamin 1500mcg / 2ml',
                'manufacturer' => 'Mankind Pharma',
                'hsn_code' => '30045020',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Injection',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // OINTMENTS, CREAMS & GELS (81-88)
            // -------------------------------------------------------------
            [
                'name' => 'Betadine Antiseptic Ointment 20g',
                'description' => 'First-aid microbicidal topical ointment for minor cuts, burns, and wounds.',
                'salt_composition' => 'Povidone-Iodine 5% w/w',
                'manufacturer' => 'Win-Medicare',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Ointment',
                'verified' => true,
            ],
            [
                'name' => 'Volini Pain Relief Gel 30g',
                'description' => 'Topical analgesic pain relief gel for joint strain, backache, and neck ache.',
                'salt_composition' => 'Diclofenac Diethylamine 1.16% + Linseed Oil + Methyl Salicylate',
                'manufacturer' => 'Sun Pharma',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Gel',
                'verified' => true,
            ],
            [
                'name' => 'Quadriderm RF Cream 10g',
                'description' => 'Broad spectrum antifungal, antibacterial, and anti-inflammatory topical skin cream.',
                'salt_composition' => 'Beclomethasone + Clotrimazole + Neomycin',
                'manufacturer' => 'Fulford India / MSD',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Cream',
                'verified' => true,
            ],
            [
                'name' => 'Silver Sulfadiazine Burn Ointment 15g (Burnol)',
                'description' => 'Topical antimicrobial cream formulated for first and second-degree burns.',
                'salt_composition' => 'Silver Sulfadiazine 1% w/w + Chlorhexidine Gluconate',
                'manufacturer' => 'Morepen Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Ointment',
                'verified' => true,
            ],
            [
                'name' => 'Clotrimazole Antifungal Cream 20g (Candid Cream)',
                'description' => 'Broad-spectrum topical imidazole antifungal cream for ringworm and athlete foot.',
                'salt_composition' => 'Clotrimazole 1% w/w',
                'manufacturer' => 'Glenmark Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Cream',
                'verified' => true,
            ],
            [
                'name' => 'Mupirocin Antibacterial Ointment 5g (T-Bact)',
                'description' => 'Topical antibiotic ointment effective against staphylococcal impetigo.',
                'salt_composition' => 'Mupirocin 2% w/w',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30042099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Ointment',
                'verified' => true,
            ],
            [
                'name' => 'Permethrin 5% Anti-Scabies Cream 30g (Permite Cream)',
                'description' => 'Synthetic pyrethroid topical cream for scabies and body lice eradication.',
                'salt_composition' => 'Permethrin 5% w/w',
                'manufacturer' => 'Galderma India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Cream',
                'verified' => true,
            ],
            [
                'name' => 'Hydrocortisone 1% Topical Skin Cream 15g (Cortizone)',
                'description' => 'Mild topical corticosteroid cream for eczema, rashes, and insect bite itching.',
                'salt_composition' => 'Hydrocortisone Acetate 1% w/w',
                'manufacturer' => 'Abbott Healthcare',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Cream',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // DROPS (89-94)
            // -------------------------------------------------------------
            [
                'name' => 'Ciplox Eye/Ear Drops 10ml',
                'description' => 'Ophthalmic and otic solution for bacterial conjunctivitis and ear canal infection.',
                'salt_composition' => 'Ciprofloxacin 0.3% w/v',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Drops',
                'verified' => true,
            ],
            [
                'name' => 'Otrivin Adult Nasal Spray Drops 10ml',
                'description' => 'Nasal decongestant for rapid nasal blockage relief caused by cold or sinusitis.',
                'salt_composition' => 'Xylometazoline Hydrochloride 0.1% w/v',
                'manufacturer' => 'GlaxoSmithKline (GSK)',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Drops',
                'verified' => true,
            ],
            [
                'name' => 'Refresh Tears Lubricating Eye Drops 10ml',
                'description' => 'Artificial tears eye drops for dry eye syndrome and screen strain soothing.',
                'salt_composition' => 'Carboxymethylcellulose Sodium 0.5% w/v',
                'manufacturer' => 'Allergan India',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Drops',
                'verified' => true,
            ],
            [
                'name' => 'Tobramycin & Dexamethasone Eye Drops (Tobradex)',
                'description' => 'Steroid and antibiotic combination ophthalmic drops for post-cataract inflammation.',
                'salt_composition' => 'Tobramycin 0.3% + Dexamethasone 0.1% w/v',
                'manufacturer' => 'Alcon Laboratories',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Drops',
                'verified' => true,
            ],
            [
                'name' => 'Waxpol Ear Drops 10ml',
                'description' => 'Ear wax softener drops for painless ear cerumen removal.',
                'salt_composition' => 'Paradichlorobenzene + Benzocaine + Chlorbutol',
                'manufacturer' => 'Wallace Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Drops',
                'verified' => true,
            ],
            [
                'name' => 'Nasivion Paediatric Nasal Drops 10ml',
                'description' => 'Gentle nasal decongestant drops formulated for infants and young children.',
                'salt_composition' => 'Oxymetazoline Hydrochloride 0.025% w/v',
                'manufacturer' => 'Procter & Gamble (P&G)',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Drops',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // INHALERS (95-97)
            // -------------------------------------------------------------
            [
                'name' => 'Asthalin Inhaler 100mcg',
                'description' => 'Bronchodilator inhaler for rapid rescue relief of asthma and bronchospasm.',
                'salt_composition' => 'Salbutamol 100mcg per dose',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Inhaler',
                'verified' => true,
            ],
            [
                'name' => 'Budecort 200 Inhaler (Budesonide 200mcg)',
                'description' => 'Inhaled corticosteroid for daily maintenance prevention of asthma flare-ups.',
                'salt_composition' => 'Budesonide 200mcg per actuation',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Inhaler',
                'verified' => true,
            ],
            [
                'name' => 'Foracort 200 Inhaler (Formoterol + Budesonide)',
                'description' => 'Combination LABA and inhaled corticosteroid for severe COPD and bronchial asthma.',
                'salt_composition' => 'Formoterol Fumarate 6mcg + Budesonide 200mcg',
                'manufacturer' => 'Cipla Ltd',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'H',
                'category' => 'Inhaler',
                'verified' => true,
            ],

            // -------------------------------------------------------------
            // POWDERS & LOTIONS (98-100)
            // -------------------------------------------------------------
            [
                'name' => 'ORSL Oral Rehydration Powder 21g',
                'description' => 'WHO-formula oral rehydration salts restoring vital electrolytes during diarrhea.',
                'salt_composition' => 'Sodium Chloride 2.6g + Potassium Chloride 1.5g + Dextrose 13.5g',
                'manufacturer' => 'Abbott Healthcare',
                'hsn_code' => '30049099',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Powder',
                'verified' => true,
            ],
            [
                'name' => 'Candid Antifungal Dusting Powder 100g',
                'description' => 'Absorbent antifungal dusting powder preventing prickly heat and fungal sweat rash.',
                'salt_composition' => 'Clotrimazole 1% w/w',
                'manufacturer' => 'Glenmark Pharmaceuticals',
                'hsn_code' => '30049099',
                'gst_rate' => 12.00,
                'drug_schedule' => 'OTC',
                'category' => 'Powder',
                'verified' => true,
            ],
            [
                'name' => 'Calamine Skin Lotion 100ml (Lacto Calamine)',
                'description' => 'Soothing lotion for oily skin, mild itching, sunburns, and allergic skin rashes.',
                'salt_composition' => 'Calamine 15% + Zinc Oxide 5% + Kaolin',
                'manufacturer' => 'Piramal Healthcare',
                'hsn_code' => '33049990',
                'gst_rate' => 18.00,
                'drug_schedule' => 'OTC',
                'category' => 'Lotion',
                'verified' => true,
            ],
        ];

        foreach ($products as $item) {
            $catName = $item['category'];
            $catId = $categoryMap[$catName] ?? null;

            UniversalProduct::create([
                'name' => $item['name'],
                'slug' => Str::slug($item['name']),
                'description' => $item['description'],
                'salt_composition' => $item['salt_composition'],
                'manufacturer' => $item['manufacturer'],
                'hsn_code' => $item['hsn_code'],
                'gst_rate' => $item['gst_rate'],
                'drug_schedule' => $item['drug_schedule'],
                'medicine_category_id' => $catId,
                'verified' => $item['verified'],
            ]);
        }
    }
}

// /php artisan db:seed --class=UniversalProductSeeder